-- CreateEnum
CREATE TYPE "NotificationType" AS ENUM ('POST_CREATED', 'POST_APPROVED', 'POST_REJECTED', 'POST_LOCKED', 'POST_UNLOCKED', 'POST_REMOVED', 'COMMENT_CREATED', 'COMMENT_REPLIED', 'POST_UPVOTED', 'COMMENT_UPVOTED', 'USER_MENTION', 'JOIN_REQUEST_CREATED', 'JOIN_REQUEST_APPROVED', 'JOIN_REQUEST_REJECTED', 'MEMBER_PROMOTED', 'MEMBER_DEMOTED', 'MEMBER_BANNED', 'MEMBER_UNBANNED', 'REPORT_CREATED', 'REPORT_RESOLVED', 'REPORT_DISMISSED', 'MODERATION_ACTION_TAKEN', 'COMMUNITY_SUSPENDED', 'COMMUNITY_REACTIVATED', 'USER_BANNED', 'USER_UNBANNED', 'ROLE_CHANGED');

-- CreateTable
CREATE TABLE "Notification" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "type" "NotificationType" NOT NULL,
    "title" TEXT,
    "message" TEXT,
    "metadata" JSONB,
    "isRead" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Notification_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "Notification_userId_createdAt_idx" ON "Notification"("userId", "createdAt");
